# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class Note(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Note - a model defined in OpenAPI

        id: The id of this Note [Optional].
        author: The author of this Note.
        date: The date of this Note.
        text: The text of this Note.
    """

    id: Optional[str] = None
    author: str
    date: datetime
    text: str

Note.update_forward_refs()
