# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class RelatedEntityRefOrValue(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RelatedEntityRefOrValue - a model defined in OpenAPI

        id: The id of this RelatedEntityRefOrValue [Optional].
        href: The href of this RelatedEntityRefOrValue [Optional].
        name: The name of this RelatedEntityRefOrValue [Optional].
        role: The role of this RelatedEntityRefOrValue.
        base_type: The base_type of this RelatedEntityRefOrValue [Optional].
        schema_location: The schema_location of this RelatedEntityRefOrValue [Optional].
        type: The type of this RelatedEntityRefOrValue [Optional].
        referred_type: The referred_type of this RelatedEntityRefOrValue [Optional].
    """

    id: Optional[str] = None
    href: Optional[str] = None
    name: Optional[str] = None
    role: str
    base_type: Optional[str] = None
    schema_location: Optional[AnyUrl] = None
    type: Optional[str] = None
    referred_type: Optional[str] = None

RelatedEntityRefOrValue.update_forward_refs()
