# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.order_item_action_type import OrderItemActionType


class RelatedServiceOrderItem(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RelatedServiceOrderItem - a model defined in OpenAPI

        item_id: The item_id of this RelatedServiceOrderItem.
        role: The role of this RelatedServiceOrderItem [Optional].
        service_order_href: The service_order_href of this RelatedServiceOrderItem [Optional].
        service_order_id: The service_order_id of this RelatedServiceOrderItem.
        item_action: The item_action of this RelatedServiceOrderItem [Optional].
        referred_type: The referred_type of this RelatedServiceOrderItem [Optional].
    """

    item_id: str
    role: Optional[str] = None
    service_order_href: Optional[str] = None
    service_order_id: str
    item_action: Optional[OrderItemActionType] = None
    referred_type: Optional[str] = None

RelatedServiceOrderItem.update_forward_refs()
