# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.service import Service


class ServiceDeleteEventPayload(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServiceDeleteEventPayload - a model defined in OpenAPI

        service: The service of this ServiceDeleteEventPayload [Optional].
    """

    service: Optional[Service] = None

ServiceDeleteEventPayload.update_forward_refs()
